<?php

/**
 * @file
 * Contains hook implementations for the ckeditor5_sections module.
 */

use Drupal\ckeditor5_sections\Field\TextLongWithSectionsItem;
use Drupal\ckeditor5_sections\Field\TextWithSummaryAndSectionsItem;

/**
 * Implements hook_views_data_alter().
 */
function ckeditor5_sections_views_data_alter(&$data) {
  // Use custom media select plugin.
  $data['media']['media_library_select_form']['field']['id'] = 'sections_media_library_select_form';
}

/**
 * Implements hook_field_info_alter().
 */
function ckeditor5_sections_field_info_alter(&$info) {
  $field_types = [
    'text_with_summary' => TextWithSummaryAndSectionsItem::class,
    'text_long' => TextLongWithSectionsItem::class,
  ];
  foreach ($field_types as $field_type => $class_name) {
    if (!empty($info[$field_type])) {
      $info[$field_type]['class'] = $class_name;
    }
  }
}