<?php

/**
 * @file
 * Contains hook implementations for the ckeditor5_sections module.
 */

use Drupal\ckeditor5_sections\Field\TextLongWithSectionsItem;
use Drupal\ckeditor5_sections\Field\TextWithSummaryAndSectionsItem;
use Drupal\ckeditor5_sections\Form\SectionsMediaLibraryUploadForm;

/**
 * Implements hook_views_data_alter().
 */
function ckeditor5_sections_views_data_alter(&$data) {
  // Use custom media select plugin.
  $data['media']['media_library_select_form']['field']['id'] = 'sections_media_library_select_form';

  $data['node_field_data']['node_library_select_form'] = $data['media']['media_library_select_form'];
  $data['node_field_data']['node_library_select_form']['title'] = t('Select Node');
  $data['node_field_data']['node_library_select_form']['real field'] = 'nid';
}

/**
 * Implements hook_module_implements_alter().
 */
function ckeditor5_sections_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'media_source_info_alter':
      $group = $implementations['ckeditor5_sections'];
      unset($implementations['ckeditor5_sections']);
      $implementations['ckeditor5_sections'] = $group;
      break;

    default:
      break;
  }
}

/**
 * Implements hook_field_info_alter().
 */
function ckeditor5_sections_field_info_alter(&$info) {
  $field_types = [
    'text_with_summary' => TextWithSummaryAndSectionsItem::class,
    'text_long' => TextLongWithSectionsItem::class,
  ];
  foreach ($field_types as $field_type => $class_name) {
    if (!empty($info[$field_type])) {
      $info[$field_type]['class'] = $class_name;
    }
  }
}

/**
 * Implements hook_media_source_info_alter().
 */
function ckeditor5_sections_media_source_info_alter(array &$sources) {
  $sources['audio_file']['forms']['media_library_add'] = SectionsMediaLibraryUploadForm::class;
  $sources['file']['forms']['media_library_add'] = SectionsMediaLibraryUploadForm::class;
  $sources['image']['forms']['media_library_add'] = SectionsMediaLibraryUploadForm::class;
  $sources['video_file']['forms']['media_library_add'] = SectionsMediaLibraryUploadForm::class;
}
